### ISSUE TITLE
[feature] Show tooltip for flower viz nodes

### ISSUE THREAD

**Issue by rapee** [electinth/civil-movement#10]
### Describe this feature

Show tooltip about the event when mouse is over.

<img width="491" alt="Screen Shot 2021-01-15 at 10 31 40" src="https://user-images.githubusercontent.com/924635/104677936-f40b1580-571c-11eb-944e-b6952a48dd97.png">

### Why is it needed?

Get the context of each event.

### Suggested solution

The tooltip component should reside outside of the flower viz (D3.js) component. The flower viz should receive a callback function to call when and where the tooltip should appear. The event info and tooltip position should be passed to the callback function.

### Related issue/PR

- #2 Flower viz

### Related Resources

- [Figma design](https://www.figma.com/file/cehtrVkenaOPVI99YMeBlB/%5BElect%5D-Civil-Movement?node-id=433%3A4085)

**Comment by rapee** [comment]
@puripant Please prepare the flower viz for mouse hover event:

> The flower viz should receive a callback function to call when the tooltip should appear.
> The event info and tooltip position should be passed to the callback function.

**Comment by Th1nkK1D** [comment]
Implemented

![image](https://user-images.githubusercontent.com/8860448/105802421-b71d0980-5fcd-11eb-84f1-e2d002b55153.png)
