### ISSUE TITLE
[feature] Create about page

### ISSUE THREAD

**Issue by rapee** [electinth/civil-movement#15]
### Describe this feature

Create an about page with contents and layout described in figma design.

![about](https://user-images.githubusercontent.com/924635/104681379-c7f39280-5724-11eb-8e82-f33f273f9421.png)

### Why is it needed?

Project about.

### Suggested solution

No.

### Related issue/PR

No.

### Related Resources

- [Figma design](https://www.figma.com/file/cehtrVkenaOPVI99YMeBlB/%5BElect%5D-Civil-Movement?node-id=456%3A1233)

**Comment by Th1nkK1D** [comment]
Page added, waiting for the final information in the contributor section
