### ISSUE TITLE
[feature] Add filter mechanic to flower visualization

### ISSUE THREAD

**Issue by Th1nkK1D** [electinth/civil-movement#16]
### Describe this feature

Update visualization on d3 side when the filter is changed

### Suggested solution

Right now filter is pass to `plot` function in `src/utils/flower-d3.js` as the 2nd parameter

```js
function plot(
  data,
  filter,
  stageElement,
  onMouseOverNode,
  onMouseOutOfNode,
  onClickNode
)
```

Filter shape is like this:

```ts
  interface Filter {
    organizers: string[];
    keyTopics: string[];
  }
```
Each filter keys is already defined in `src/constants/filter.ts`. Please import from there.

### Related issue/PR
#2 #3

**Comment by puripant** [comment]
@Th1nkK1D I have tried to watch `filter` change in `flower-d3.js` but so far all attempts have failed. If possible, can we switch to callback mechanism for filtering like mouseover or tooltip? This requires changes in the dropdown component though.

**Comment by Th1nkK1D** [comment]
> @Th1nkK1D I have tried to watch `filter` change in `flower-d3.js` but so far all attempts have failed. If possible, can we switch to callback mechanism for filtering like mouseover or tooltip? This requires changes in the dropdown component though.

Yes we can do that for now. From the `plot` function, you can return `onFilterChange` which accept filters (an array of filter string) as an argument

```js
const onFilterChange = (filters) => {
// Logic to apply new filters
}

return { onfilterChange }
```

Or if you don't have a plan to do it today, I can set it up tomorrow.

**Comment by puripant** [comment]
@Th1nkK1D Can you set it up for me? I will have some time to do this by the end of this week.

**Comment by Th1nkK1D** [comment]
@puripant

**Comment by Th1nkK1D** [comment]
@puripant I added the following code to the bottom of `flower-d3.js`
```js
const onFilterChange = (filters) => {
    // Logic to apply new filters
    console.log('filter changed', filters);
  };

return onFilterChange;
```
This onFilterChange is trigger once on the first render with default filters and then every time when the filters are changed. Here is the filters parameter type and example value:
```js
filters = {
  organizers: ["youth", "civil", "party", "government"],
  keyTopics: ["justice", "government", "constitution"]
}
```
(note that we didn't include the time filter yet, but we might be able to add it later)

**Comment by Th1nkK1D** [comment]
@puripant I found out that filter mechanics is not that difficult, so I try to implement it, and now it is working nicely as far as I test. Maybe you want to review the code just in case there is a better way. Everything start from `onFilterChange` function. Then you can close the issue if everything is ok.

**Comment by puripant** [comment]
Everything seems to be okay. I particularly like `keyTopics.some((topic) => key_topic.includes(topic))`. Thanks!
