### ISSUE TITLE
[improvement] Remove line chart smoothing

### ISSUE THREAD

**Issue by Th1nkK1D** [electinth/civil-movement#22]
Remove line smoothing since it might confuse the user.
![image](https://user-images.githubusercontent.com/8860448/107473484-60a1f480-6ba3-11eb-9a45-fce8f8bf0768.png)

**Comment by thasarito** [comment]
try filling missing date with count 0 and the chart will look like this.

![image](https://user-images.githubusercontent.com/20541527/107845822-6d5a5e80-6dd6-11eb-8659-3b95c39a0802.png)

**Comment by Th1nkK1D** [comment]
This looks close. but I wonder why the line doesn't look straight, especially the first peak...

**Comment by thasarito** [comment]
because curve function. I will remove it.

![image](https://user-images.githubusercontent.com/20541527/107845919-320c5f80-6dd7-11eb-88d1-3454c3dc8f9d.png)

**Comment by thasarito** [comment]
I got the filter function wrong. This look wayyy better haha.

![image](https://user-images.githubusercontent.com/20541527/107852951-6863d200-6e0b-11eb-9774-ed9558c8e775.png)

**Comment by Th1nkK1D** [comment]
this looks awesome!
