### ISSUE TITLE
Wrap flower visualization in svelte as component

### ISSUE THREAD

**Issue by rapee** [electinth/civil-movement#3]
# Related Issues

#2

**Comment by Th1nkK1D** [comment]
@puripant Sorry, I forgot to mention that I already add `src/components/landing/flower-visualization.svelte` component. Right now it render d3 with simple plot that I took the example code from the internet. You can try to migrate the visualizaiton or we can do it together next week 😄

**Comment by thasarito** [comment]
Here is another [d3+svelte example](https://svelte.dev/repl/8262eb73a08f48adba8e0b706c1a939f?version=3.22.1.), which use template of the framework itself to render (instead of using `d3-selection`) and only use `d3` to calculate the position of the element.

**Comment by Th1nkK1D** [comment]
@thasarito I tried to refactor d3 code to be more template-centric like your suggestion and it's not easy LOL. Might do that if we could finish the project before time.
