### ISSUE TITLE
[feature] Flower vis auto plays on first run

### ISSUE THREAD

**Issue by rapee** [electinth/civil-movement#5]
### Describe this feature

When page loaded completely on home page, the flower viz should start playing automatically.
Each node appears according to its date.

Also, it should have a way to expose `current date` value so **the timeline component** can sync the slider head.

![chart](https://user-images.githubusercontent.com/924635/104675963-1438d580-5719-11eb-9245-a2a309fc90a1.png)

### Why is it needed?

It'll look wonderful 🌷 

### Suggested solution

Please suggest.

### Related issue/PR

No.

**Comment by puripant** [comment]
[The current test version](http://puripant.ruchikachorn.com/elect-civic-movement-test/) doesn't display the nodes according to the time but according to the order of events. The main reason for this after confirming with the designer is that there is a big gap of events during the first COVID-19 lockdown (Q2 of 2020) so the viewer may lose interest. Anyway, with the slider, it can be okay as the slider keeps moving even when no new node is showing.

**Comment by Th1nkK1D** [comment]
Look like this issue can be closed. Since the flower transition is already working and it's not related to the timeline anymore #17
