### ISSUE TITLE
[feature] Timeline date range controller

### ISSUE THREAD

**Issue by rapee** [electinth/civil-movement#7]
### Describe this feature

Create a timeline date range controller to visualize "time" in this civil movement.

It will be used for 2 purposes:

1. Flower viz auto plays on first run [#5]. It should be synced with this controller.
2. User can drag start and end handlers, and the date range itself.  The flower viz will show only the nodes that are inside the range.

When user drags, the controller should pass start-end date range to the Flower viz [#2]

![chart](https://user-images.githubusercontent.com/924635/104675963-1438d580-5719-11eb-9245-a2a309fc90a1.png)

From left to right: play button, pause button, drag handler, reply button.

<img width="505" alt="Screen Shot 2021-01-15 at 10 09 25" src="https://user-images.githubusercontent.com/924635/104676474-0899de80-571a-11eb-9f3d-35a1e1842c29.png">

### Why is it needed?

It looks cool than other websites.

### Suggested solution

- It is arguable that the controller should be synced on the flower viz's first run. If you consider it's too difficult, it's also acceptable to hide the controller first, then only after the auto play completes that we'll show the controller.

### Related issue/PR

- #2 
- #5 

### Related Resources

- [Figma design](https://www.figma.com/file/cehtrVkenaOPVI99YMeBlB/%5BElect%5D-Civil-Movement?node-id=412%3A1337)

**Comment by thasarito** [comment]
To-Dos:

- [x] add tooltips
- [x] make timeline's width scaled by number of days in month
- [x] add play pause functionality
