### ISSUE TITLE
[feature] Line chart for movement visualization

### ISSUE THREAD

**Issue by rapee** [electinth/civil-movement#8]
### Describe this feature

Create a line chart component to visualize movement's volume over the time.

This component will be used 2 times:

- Home page: right on top of The Timeline component [#7].
- Summary page: as a page's main viz.

So ideally, this component should be reusable with little modification for both use cases.

On home page:

![chart](https://user-images.githubusercontent.com/924635/104675963-1438d580-5719-11eb-9245-a2a309fc90a1.png)

On summary page:
<img width="755" alt="Screen Shot 2021-01-15 at 10 22 59" src="https://user-images.githubusercontent.com/924635/104677479-0df82880-571c-11eb-9252-807390a16201.png">

### Why is it needed?

It make people get the idea of how large the movements are.

### Suggested solution

Please suggest.

### Related issue/PR

- #7 Timeline controller

### Related Resources

- [Home page](https://www.figma.com/file/cehtrVkenaOPVI99YMeBlB/%5BElect%5D-Civil-Movement?node-id=412%3A1337)
- [Summary page](https://www.figma.com/file/cehtrVkenaOPVI99YMeBlB/%5BElect%5D-Civil-Movement?node-id=412%3A974)

**Comment by thasarito** [comment]
To-Dos:

Flower Page:

- [ ] add title on flower page

Summary Page:

- [x] add tooltip
- [x] add axis
